# Generated by Django 2.1.5 on 2019-03-06 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jsonfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=500)),
                ('designación', models.CharField(blank=True, max_length=500)),
                ('contador_horario_grupo', models.CharField(blank=True, max_length=500)),
                ('contador_horario_motor', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('nivel_fuel', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('temp_agua', models.CharField(blank=True, max_length=200)),
                ('v_bat', models.CharField(blank=True, max_length=200)),
                ('temp_aceite', models.BooleanField(default=False)),
                ('presión_aceite_bar', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('frec_hz', models.CharField(blank=True, max_length=200)),
                ('v1', models.CharField(blank=True, max_length=200)),
                ('p_kw', models.CharField(blank=True, max_length=200)),
                ('q_kvar', models.CharField(blank=True, max_length=200)),
                ('s_kvar', models.CharField(blank=True, max_length=200)),
                ('tensión_ext', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
