# Generated by Django 2.1.5 on 2019-02-22 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20190221_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='grupo',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='grupo_id',
            new_name='n_serie',
        ),
    ]
