# Generated by Django 2.1.5 on 2019-03-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceid', models.CharField(max_length=500)),
                ('type_communication', models.CharField(max_length=500)),
                ('dev_range', models.FloatField()),
                ('message', models.CharField(blank=True, max_length=500)),
                ('active', models.BooleanField(default=False)),
                ('alarm', models.BooleanField(default=False)),
            ],
        ),
    ]
