from django.db import models
from datetime import datetime
from clientes.models import Cliente

class Grupo(models.Model):
    modelo = models.CharField(max_length=500)
    n_serie = models.CharField(max_length=200)
    n_contacto = models.CharField(max_length=200, blank=True)
    fecha_avería = models.DateTimeField(default=datetime.now, blank=True)
    última_revisión = models.DateTimeField(default=datetime.now)
    código_avería = models.CharField(max_length=200, blank=True)
    cliente = models.ForeignKey(Cliente, on_delete=models.DO_NOTHING)
    averiado = models.BooleanField(default=False)
    puesta_en_marcha = models.DateTimeField(default=datetime.now, blank=True)
    latitud = models.CharField(max_length=200, blank=True)
    longitud = models.CharField(max_length=200, blank=True)
    altitud = models.CharField(max_length=200, blank=True)
    ciudad = models.CharField(max_length=200)
    kva = models.CharField(max_length=200, blank=True)
    tensión = models.CharField(max_length=200, blank=True)
    frecuencia = models.CharField(max_length=200, blank=True)
    anomalias = models.CharField(max_length=200, blank=True)
    horas_funcionamiento = models.CharField(max_length=200, blank=True)
    motor_modelo = models.CharField(max_length=200, blank=True)
    motor_n_serie = models.CharField(max_length=200, blank=True)
    alternador_modelo = models.CharField(max_length=200, blank=True)
    alternador_n_serie = models.CharField(max_length=200, blank=True)
    equipo_control = models.CharField(max_length=200, blank=True)
    tensión_cc = models.CharField(max_length=200, blank=True)
    num_baterias = models.CharField(max_length=200, blank=True)
    modelo_baterías = models.CharField(max_length=200, blank=True)
    litros_depósito = models.CharField(max_length=200, blank=True)
    litros_aceite = models.CharField(max_length=200, blank=True)
    litros_refrigerante = models.CharField(max_length=200, blank=True)
    filtros_aceite_cant = models.CharField(max_length=200, blank=True)
    filtros_aceite_modelo = models.CharField(max_length=200, blank=True)
    filtros_combustible_cant = models.CharField(max_length=200, blank=True)
    filtros_combustible_modelo = models.CharField(max_length=200, blank=True)
    filtros_agua_cant = models.CharField(max_length=200, blank=True)
    filtros_agua_modelo = models.CharField(max_length=200, blank=True)
    filtros_aire_cant = models.CharField(max_length=200, blank=True)
    filtros_aire_modelo = models.CharField(max_length=200, blank=True)
    otros_respuestos = models.CharField(max_length=800, blank=True)
    descripción = models.TextField(blank=True)
    foto_principal = models.ImageField(upload_to='photos/%Y/%m/%d/')
    foto_equipo_control_1 = models.ImageField(upload_to='photos/%Y/%m/%d/')
    foto_equipo_control_2 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    foto_motor_1 = models.ImageField(upload_to='photos/%Y/%m/%d/')
    foto_motor_2 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    foto_alternador_1 = models.ImageField(upload_to='photos/%Y/%m/%d/')
    foto_alternador_2 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_8 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_9 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_10 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_11 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_12 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_13 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    def __str__(self):
        return self.modelo