# Generated by Django 2.1.5 on 2019-01-30 09:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_id', models.CharField(max_length=500)),
                ('propietario', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('latitud', models.CharField(max_length=200)),
                ('longitud', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('cp', models.CharField(max_length=20)),
                ('descripción', models.TextField(blank=True)),
                ('averiado', models.BooleanField(default=False)),
                ('puesta_en_marcha', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('foto_principal', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('foto_equipo_control_1', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('foto_equipo_control_2', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('foto_motor_1', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('foto_motor_2', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('foto_alternador_1', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('foto_alternador_2', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_8', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_9', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_10', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_11', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_12', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_13', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.Cliente')),
            ],
        ),
    ]
