# Generated by Django 2.1.5 on 2019-01-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupo',
            old_name='grupo_id',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='grupo',
            name='foto_alternador_2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='foto_equipo_control_2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='foto_motor_2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
