# Generated by Django 2.1.5 on 2019-01-30 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0002_auto_20190130_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='title',
        ),
    ]
