# Generated by Django 2.1.5 on 2019-02-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0004_auto_20190215_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupo',
            old_name='timestamp',
            new_name='ultima_revisión',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='alarma_general',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='bajo_nv_bateria',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='bajo_nv_gasoil',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='bajo_nv_refrigerante',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='carga_bateria',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='cp',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='fallo_arranque',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='fallo_caldeo',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='fallo_cargador',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='fallo_general',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='grupo_en_marcha',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='hz',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='kw',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='min_frecuencia',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='modo_auto',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='modo_manual',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='modo_test',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='presion_aceite',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='propietario',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='sobre_frecuencia',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='sobrecarga',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='sobretension',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='stop',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='subtension',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='temp_agua',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='tension_bateria',
        ),
        migrations.AddField(
            model_name='grupo',
            name='alternador_modelo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='grupo',
            name='alternador_n_serie',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='grupo',
            name='altitud',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='grupo',
            name='anomalias',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='grupo',
            name='equipo_control',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='grupo',
            name='filtros_aceite_cant',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='grupo',
            name='filtros_aceite_modelo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='grupo',
            name='filtros_agua_cant',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='grupo',
            name='filtros_agua_modelo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='grupo',
            name='filtros_aire_cant',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='grupo',
            name='filtros_aire_modelo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='grupo',
            name='filtros_combustible_cant',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='grupo',
            name='filtros_combustible_modelo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='grupo',
            name='frecuencia',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='grupo',
            name='horas_funcionamiento',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='grupo',
            name='litros_aceite',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='grupo',
            name='litros_deposito',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='grupo',
            name='litros_refrigerante',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='grupo',
            name='modelo_baterias',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='grupo',
            name='motor_modelo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='grupo',
            name='motor_n_serie',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='grupo',
            name='n_serie',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='grupo',
            name='num_baterias',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='grupo',
            name='otros_respuestos',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='grupo',
            name='potencia_kva',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='grupo',
            name='tensión',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='grupo',
            name='tensión_cc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='latitud',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='longitud',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='modelo',
            field=models.CharField(max_length=500),
        ),
    ]
