# Generated by Django 2.1.5 on 2019-02-18 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0006_auto_20190218_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupo',
            old_name='litros_deposito',
            new_name='litros_depósito',
        ),
        migrations.RenameField(
            model_name='grupo',
            old_name='modelo_baterias',
            new_name='modelo_baterías',
        ),
        migrations.RenameField(
            model_name='grupo',
            old_name='ultima_revisión',
            new_name='última_revisión',
        ),
    ]
