# Generated by Django 2.1.5 on 2019-02-19 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0007_auto_20190218_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='n_contacto',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='n_serie',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='última_revisión',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
