# Generated by Django 2.1.5 on 2019-02-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0008_auto_20190219_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='código_avería',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
