# Generated by Django 2.1.5 on 2019-02-19 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0009_grupo_código_avería'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='fecha_avería',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
