# Generated by Django 2.1.5 on 2019-01-30 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre_contacto',
            new_name='name',
        ),
    ]
