# Generated by Django 2.1.5 on 2019-01-30 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20190130_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='grupo_10_id',
            new_name='grupo_1',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='grupo_11_id',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='grupo_12_id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='grupo_13_id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='grupo_14_id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='grupo_15_id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='grupo_16_id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='grupo_17_id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='grupo_18_id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='grupo_19_id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='grupo_1_id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='grupo_20_id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='grupo_21_id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='grupo_2_id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='grupo_3_id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='grupo_4_id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='grupo_5_id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='grupo_6_id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='grupo_7_id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='grupo_8_id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='grupo_9_id',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='name',
        ),
    ]
