# Generated by Django 2.1.5 on 2019-02-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20190130_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='alerta',
            field=models.BooleanField(default=False),
        ),
    ]
