# Generated by Django 2.1.5 on 2019-02-15 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20190214_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='alarma_general',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='bajo_nv_bateria',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='bajo_nv_gasoil',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='bajo_nv_refrigerante',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='carga_bateria',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fallo_arranque',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fallo_caldeo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fallo_cargador',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fallo_general',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='grupo_en_marcha',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='hz',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='kw',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='min_frecuencia',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='modo_auto',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='modo_manual',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='modo_test',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='presion_aceite',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='sobre_frecuencia',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='sobrecarga',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='sobretension',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='stop',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='subtension',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='temp_agua',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tension_bateria',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='timestamp',
        ),
    ]
