# Generated by Django 2.1.5 on 2019-03-05 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20190215_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cliente_id',
            new_name='empresa',
        ),
    ]
